settings:
  title: '状态'
  url: '' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有站点工作正常'
  notAllmonitorsOperational: '部分站点工作异常'
  monitorLabelOperational: '正常'
  monitorLabelNotOperational: '异常'
  monitorLabelNoData: '暂无数据'
  dayInHistogramNoData: '暂无数据'
  dayInHistogramOperational: '全部正常'
  dayInHistogramNotOperational: ' 事故' # xx incident(s) recorded

monitors:
  
  - id: blog-ghpages
    name: Github Pages
    url: 'https://qwerx29.github.io/'
    method: GET
    expectStatus: 200
    
  - id: blog-vercel
    name: Vercel
    url: 'https://phantasus.vercel.app/'
    method: GET
    expectStatus: 200
    
  - id: blog-netlify
    name: Netlify
    url: 'https://phantasus.netlify.app/'
    method: GET
    expectStatus: 200

  - id: blog-cf
    name: Cloudflare Pages
    url: 'https://phantasus-2.pages.dev/'
    method: GET
    expectStatus: 200
